spring:
  datasource:
    url: jdbc:h2:file:~/H2DB/beerdb;AUTO_SERVER=TRUE;
    username: beer
    password: beer
    driver-class-name: org.h2.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none